baseurl = "https://mailund.dk/"
title = "Mailund on the Internet"
copyright = "Copyright &copy; 2018 - Thomas Mailund"
theme = "hugo-kiera"

canonifyurls = true
ignoreFiles = []

googleAnalytics = "UA-10582357-1"
disqusShortname = "mailund-dk"

paginate = 20
summaryLength = 30
pygmentsCodeFences = true
pygmentsStyle = "friendly"

[author]
    name = "Thomas Mailund"
    github = "mailund"
    twitter = "ThomasMailund"
    linkedin = "thomas-mailund-94153b1"
    facebook = "mailund"
    patreon = "mailund"
    goodreads = "15484380.Thomas_Mailund"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    tagline = "On Writing, Science, Programming and more"

    googlefonts = ["Droid Sans", "Fira Mono"]
    fontbody = 'Droid Sans'
    fontcode = 'Fira Code'

[[menu.main]]
  name = "Posts"
  identifier = "post"
  weight = 2
  url = "/posts"
