baseurl = "https://mailund.dk/"
title = "Mailund on the Internet"
copyright = "Copyright &copy; 2018 - Thomas Mailund"
theme = "hugo-kiera"

canonifyurls = true
ignoreFiles = []

googleAnalytics = "UA-10582357-1"
disqusShortname = "mailund-dk"

paginate = 10
summaryLength = 100
pygmentsCodeFences = true
pygmentsStyle = "friendly"

[author]
    name = "Thomas Mailund"
    github = "mailund"
    twitter = "ThomasMailund"
    linkedin = "thomas-mailund-94153b1"
    facebook = "mailund"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    tagline = "On Writing, Science, Programming and more"
