baseurl = "https://mailund.dk/"
title = "Mailund on the Internet"
copyright = "Copyright &copy; 2020-2025 - Thomas Mailund"
theme = "hugo-kiera"

canonifyurls = true
ignoreFiles = []


pagination.pagerSize = 20
summaryLength = 30
pygmentsCodeFences = true
pygmentsStyle = "borland"

ignoreLogs = ['warning-goldmark-raw-html', 'shortcode-x-getremote']

googleAnalytics = "386493837"

[services]
  [services.disqus]
    shortname = "mailund-dk"

[frontmatter]
  newContentEditor = "index.md"

[author]
    name = "Thomas Mailund"
    github = "mailund"
    twitter = "ThomasMailund"
    linkedin = "thomas-mailund-94153b1"
    facebook = "mailund"
    patreon = "mailund"
    goodreads = "15484380.Thomas_Mailund"
    stackoverflow = "2170269/thomas-mailund"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    tagline = "On Writing, Science, Programming and more"

    googlefonts = ["Droid Sans", "Fira Mono"]
    fontbody = 'Droid Sans'
    fontcode = 'Fira Code'

[[menu.main]]
  name = "Posts"
  identifier = "post"
  weight = 2
  url = "/posts"
